[package]
name = "dockworker"
description = "Docker daemon API client. (a fork of Faraday's boondock)"
version = "0.0.18"
authors = ["eldesh <nephits@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/eldesh/dockworker"
repository = "https://github.com/eldesh/dockworker"
documentation = "https://docs.rs/dockworker"
readme = "README.md"
keywords = ["docker"]

[badges]
appveyor = { repository = "eldesh/dockworker", branch = "master", service = "github" }
circle-ci = { repository = "eldesh/dockworker" }
maintenance = { status = "actively-developed" }

[features]
# OpenSSL is fairly hard to build on certain platforms, especially if you
# want to produce release binaries. So we disable it by default.
default = []
experimental = []

# Enable OpenSSL both directly and for Hyper.
ssl = ["openssl", "native-tls", "hyper-tls"]

[dependencies]
chrono = "0.4.6"
thiserror = "1.0"
backtrace-sys = "=0.1.23"
futures = "0.1"
http = "0.1"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
openssl = { version = "0.10", optional = true }
hyperx = "0.14"
hyper-tls = { version = "0.3", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.2.2"
byteorder = "1.1.0"
tar = "0.4"
tokio = "0.1"
log = "0.4"
mime = "0.3"
native-tls = { version = "0.2", optional = true }
nix = "0.15"
base64 = "0.9.2"
dirs = "1.0.0"

[dev-dependencies]
env_logger = "0.5"
rand = "0.5"

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.6"
unix_socket = "0.5.0"

[target.'cfg(windows)'.dependencies]
named_pipe = "0.2.2"

