[package]
name = "dockworker"
description = "Docker daemon API client. (a fork of Faraday's boondock)"
version = "0.0.1"
authors = ["eldesh <nephits@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/eldesh/dockworker"
repository = "https://github.com/eldesh/dockworker"
documentation = "https://docs.rs/dockworker"
readme = "README.md"
keywords = ["docker"]

[badges]
appveyor = { repository = "eldesh/dockworker", branch = "master", service = "github" }
circle-ci = { repository = "eldesh/dockworker" }
maintenance = { status = "actively-developed" }

[features]
# OpenSSL is fairly hard to build on certain platforms, especially if you
# want to produce release binaries.  So we enable it by default, but allow
# it to be excluded using `default-features = false`.
default = ["ssl"]

# Enable OpenSSL both directly and for Hyper.
ssl = ["openssl", "hyper/ssl"]

[dependencies]
error-chain = "0.5.0"
hyper = { version = "0.9", default-features = false }
openssl = { version = "0.7", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.2.2"
byteorder = "1.1.0"
tar = "0.4"
log = "0.4"
nix = "0.11"

[dev-dependencies]
env_logger = "0.5"

[target.'cfg(unix)'.dependencies]
unix_socket = "0.5.0"

[target.'cfg(windows)'.dependencies]
named_pipe = "0.2.2"
