[package]
name = "dockworker"
description = "Docker daemon API client. (a fork of Faraday's boondock)"
version = "0.0.20"
authors = ["takayuki goto <takayuki@idein.jp>"]
license = "Apache-2.0"
homepage = "https://github.com/Idein/dockworker"
repository = "https://github.com/Idein/dockworker"
documentation = "https://docs.rs/dockworker"
readme = "README.md"
keywords = ["docker"]
edition = "2018"

[badges]
appveyor = { repository = "eldesh/dockworker", branch = "master", service = "github" }
circle-ci = { repository = "Idein/dockworker" }
maintenance = { status = "actively-developed" }

[features]
# OpenSSL is fairly hard to build on certain platforms, especially if you
# want to produce release binaries. So we disable it by default.
default = []
experimental = []

# Enable OpenSSL both directly and for Hyper.
ssl = ["openssl", "native-tls", "hyper-tls"]

[dependencies]
chrono = "0.4"
failure = "0.1"
backtrace-sys = "=0.1.23"
futures = "0.3"
http = "0.2"
hyper = "0.13"
openssl = { version = "0.10", optional = true }
hyperx = "1"
hyper-tls = { version = "0.4", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
byteorder = "1"
tar = "0.4"
tokio = { version = "0.2", features = ["full"] }
log = "0.4"
mime = "0.3"
native-tls = { version = "0.2", optional = true }
nix = "0.15"
base64 = "0.9"
dirs = "1"

[dev-dependencies]
failure = "0.1"
env_logger = "0.8"
rand = "0.5"

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.7"
unix_socket = "0.5"

[target.'cfg(windows)'.dependencies]
named_pipe = "0.2"

